# Generated by Django 3.0 on 2019-12-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191210_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(default=1221, unique=True),
            preserve_default=False,
        ),
    ]
